name: flutter_back4app
description: A Flutter application with Back4App integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^9.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.0
  connectivity_plus: ^6.0.3
  package_info_plus: ^5.0.1
  intl: ^0.20.2
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true